[tools]

lua = "5.4.7"
python = "3.12.13"
ruby = "3.4.9"
uv = "latest"

"pipx:changes-semver" = "6"
"pipx:inseven-build-tools" = "1"

[settings]

minimum_release_age_excludes = ["pipx:changes-semver", "pipx:inseven-build-tools"]
