# Copyright (c) 2021-2022 Jason Morley, Tom Sutcliffe
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

skip_docs

lane :upload do |options|
    api_key = app_store_connect_api_key(
        key_id: options[:api_key_id],
        issuer_id: options[:api_key_issuer_id],
        key_filepath: options[:api_key],
        duration: 1200,
        in_house: false
    )
    upload_to_testflight(
        api_key: api_key,
        skip_submission: true,
        ipa: options[:ipa],
        notify_external_testers: false,
        changelog: options[:changelog],
        beta_app_description: "Runtime and viewer for EPOC programs and files",
        beta_app_review_info: {
            notes: "OPL is a runtime and viewer for files and programs from the 90s-era Psion palmtop computers running the EPOC operating system. It lets users add and browse folders on their phone and view files that are in original EPOC formats. It is intended to let users of these early portable computers access files and data that might be long-forgotten and thought lost. For example, users can view and export image files from those original machines (.mbm), sound files, etc, and scripts they might have written (.opo). The app ships with examples of these files and scripts to help users get started and understand how it works. You can find these in the 'Files' and 'Scripts' sections of the app. Tapping the files you find in these sections should let you explore and exercise the functionality provided. Thanks for the review!"
        }
    )
end
