# Copyright (C) 2021-2026 Jason Morley, Tom Sutcliffe
# See LICENSE file for license information.

QT += testlib

greaterThan(QT_MAJOR_VERSION, 5): QT += core5compat

CONFIG += c++17 testcase no_testcase_installs cmdline

# On mac generally it's _always_ the case that Xcode is more recent than Qt is happy with...
macx:CONFIG += sdk_no_version_check

TARGET = opolua-unittest

!windows:DEFINES += LUA_USE_POSIX

INCLUDEPATH += ../core/shared/include ../dependencies/LuaSwift/Sources/CLua/lua

HEADERS += \
    asynchandle.h \
    oplruntime.h

SOURCES = \
    ../core/shared/src/oplfns.c \
    filesystem.cpp \
    lua.cpp \
    luasupport.cpp \
    oplkeycode.cpp \
    oplruntime.cpp \
    test.cpp

# Generated by luafiles.pro
LUA_QRC = $$OUT_PWD/luafiles.qrc
LUA_TEST_QRC = $$OUT_PWD/luafiles_test.qrc

RESOURCES += \
    $$LUA_QRC \
    $$LUA_TEST_QRC
